"""Build the reviewed 33-slot B4-A proposition map from current canonical dependencies."""

from __future__ import annotations

import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))

from qa_common import DATA, ROOT, load_json, load_records, write_json


SOURCE_MAIN_SHA = "48ba80204c4ae71795802f3b5177bf3b071b5e63"
OUTPUT = ROOT / "audits" / "coverage" / "2026-09-01" / "B4-A-PROPOSITION-MAP-FINAL.json"


def s(
    question_id: str,
    area: int,
    topic: str,
    family_id: str,
    proposition: str,
    actor: str,
    trigger: str,
    jurisdiction: str,
    exception: str,
    reasoning_task: str,
    rule_ids: list[str],
    closest: list[str],
    novelty: str,
    signals: list[str],
    question_type: str,
    difficulty: int,
    multi_rule: bool,
) -> dict:
    return {
        "question_id": question_id,
        "area": area,
        "topic": topic,
        "family_id": family_id,
        "exact_legal_proposition": proposition,
        "actor": actor,
        "trigger": trigger,
        "jurisdiction": jurisdiction,
        "exception_or_distinction": exception,
        "reasoning_task": reasoning_task,
        "rule_ids": rule_ids,
        "closest_existing_question_ids": closest,
        "novelty_rationale": novelty,
        "real_exam_signal_support": signals,
        "planned_question_type": question_type,
        "planned_difficulty": difficulty,
        "multi_rule": multi_rule,
    }


SLOTS = [
    s("MA-Q-0407", 1, "Licensure", "EXP1_0108_PHARMACIST_CE_ANNUAL",
      "연간 20 CE hours 중 home study 또는 mediated instruction은 최대 15 hours만 인정되고 pharmacy law는 최소 2 hours가 필요하다.",
      "Pharmacist", "연간 CE를 갱신에 적용", "MA", "Board가 승인한 extenuating-circumstances 절차는 별도이다.",
      "총시간, modality cap, pharmacy-law minimum을 동시에 계산한다.", ["MA-PHARMACIST-CE"],
      ["MA-Q-0079", "MA-Q-0256"], "기존 문항은 annual total 또는 daily cap을 물었고 home-study cap과 law minimum의 결합은 다루지 않았다.",
      ["precise_qualifier_and_scope_wording"], "SBA", 3, False),
    s("MA-Q-0408", 1, "Licensure", "B3A_0260_MA_CE_RECORD_CONTENT",
      "완료한 CE가 연간 요건에 포함되더라도 증빙은 completion date부터 최소 2년 보존하고 Board request 또는 random audit에 제출해야 한다.",
      "Pharmacist", "CE audit 요청", "MA", "credit 충족과 documentation 보존은 서로 대체되지 않는다.",
      "CE completion과 record-retention/production duty를 별도로 판정한다.", ["MA-PHARMACIST-CE", "MA-CE-RECORDKEEPING"],
      ["MA-Q-0260"], "기존 문항은 record contents만 다뤘고 earned credit와 2-year retention을 함께 적용하지 않았다.",
      ["exception_condition_documentation"], "SATA", 4, True),
    s("MA-Q-0409", 1, "Licensure", "B3A_0261_MA_CE_PROVIDER_CLOCKS",
      "current ACPE 또는 AMA CME Category 1 approval과 good standing을 문서로 입증한 provider는 authorized provider로 간주될 수 있다.",
      "CE provider", "외부 provider program의 credit 인정 요청", "MA", "기관명만으로 자동 인정되지 않고 current approval와 good standing 증빙이 필요하다.",
      "automatic-recognition 경로와 일반 30-day application 경로를 구분한다.", ["MA-CE-PROVIDER-APPROVAL"],
      ["MA-Q-0261"], "기존 문항은 일반 application/appeal clocks를 물었고 current national approval 경로를 다루지 않았다.",
      ["precise_qualifier_and_scope_wording"], "SBA", 5, False),
    s("MA-Q-0410", 1, "Technician scope", "EXP1_0103_TECH_CLINICAL_JUDGMENT",
      "Certified technician도 protocol 또는 pharmacist availability만으로 DUR 판단, clinical conflict resolution, therapy modification, counseling, final validation을 수행할 수 없다.",
      "Certified pharmacy technician", "unresolved DUR alert 처리 요청", "MA", "mechanical data collection과 pharmacist professional judgment를 구분한다.",
      "실제 요청된 행위가 허용된 technical task인지 금지된 judgment인지 분류한다.", ["MA-CERT-TECH-SCOPE"],
      ["MA-Q-0075"], "기존 문항은 trainee를 중심으로 했고 certified technician에 대한 protocol-delegation 주장을 다루지 않았다.",
      ["actor_role_distinctions"], "SBA", 4, False),
    s("MA-Q-0411", 1, "Technician scope", "B3A_0234_MA_CERT_TECH_NEW_RX_INFO",
      "Certified technician은 자신을 식별하고 pharmacist-on-duty approval 아래 refill authorization을 요청하거나 누락 정보를 받을 수 있지만 therapy modification 또는 counseling은 할 수 없다.",
      "Certified pharmacy technician", "prescriber office에 refill authorization 요청", "MA", "일반 technician의 unchanged-refill processing과 certified-technician의 communication scope를 구분한다.",
      "여러 통화 행위 중 허용되는 행위와 professional judgment 행위를 분리한다.", ["MA-CERT-TECH-SCOPE"],
      ["MA-Q-0234", "MA-Q-0235"], "기존 문항은 new-Rx information과 Schedule VI transfer였고 refill-authorization request branch는 미검증이다.",
      ["actor_role_distinctions"], "SATA", 4, False),
    s("MA-Q-0412", 1, "Pharmacy personnel", "B3A_0240_MA_TECH_LICENCE_LAPSE",
      "Technician licence가 2년을 초과해 lapse되면 Board는 additional conditions를 부과할 수 있고 renewal 전 practice는 허용되지 않는다.",
      "Pharmacy technician", "2년 초과 lapse 후 복귀", "MA", "Board가 조건을 요구할 수 있다는 규정이지 특정 시험을 자동으로 의무화하는 규정은 아니다.",
      "짧은 lapse fee pathway와 >2-year Board-conditions pathway를 구분한다.", ["MA-TECH-LICENSE-RENEWAL"],
      ["MA-Q-0240"], "기존 문항은 3주 lapse 중 practice를 물었고 >2-year branch를 다루지 않았다.",
      ["actor_role_distinctions", "exception_condition_documentation"], "SBA", 4, False),
    s("MA-Q-0413", 1, "Pharmacy personnel", "B3A_0232_MA_RATIO_EXCLUDED_STAFF",
      "Cashier는 professional capacity로 pharmacist를 지원하지 않는 동안만 ratio에서 제외되며 prescription data entry를 시작하면 실제 기능에 따라 ratio와 scope를 다시 평가해야 한다.",
      "Cashier acting as support personnel", "cashier가 prescription data entry를 시작", "MA", "직함이 아니라 실제 수행 기능이 exclusion과 허용 scope를 결정한다.",
      "role change 시 ratio 포함 여부와 수행 task의 적법성을 연속 판정한다.", ["MA-SUPPORT-PERSONNEL-RATIO", "MA-TECH-SCOPE"],
      ["MA-Q-0231", "MA-Q-0232"], "기존 cashier scenario는 professional work를 전혀 하지 않았고 role transition을 다루지 않았다.",
      ["actor_role_distinctions", "natural_multi_rule_scenarios"], "SATA", 4, True),
    s("MA-Q-0414", 1, "Licensure", "B3A_0254_MA_REGISTRATION_LAPSE_LADDER",
      "Pharmacist registration이 60일 초과 2년 미만 lapse되면 conditional renewal 경로이고, >2 years branch의 MPJE requirement와 구분되며 renewal 전 practice는 허용되지 않는다.",
      "Pharmacist", "61일 lapse 직후 복귀 시도", "MA", "<=60 days, >60 days, >2 years의 서로 다른 branches를 구분한다.",
      "정확한 lapse 기간을 분류한 뒤 renewal 조건과 practice consequence를 적용한다.", ["MA-PHARMACIST-REGISTRATION-RENEWAL"],
      ["MA-Q-0254"], "기존 문항은 약 30개월 lapse를 물었고 61-day boundary를 다루지 않았다.",
      ["precise_qualifier_and_scope_wording"], "SBA", 5, False),
    s("MA-Q-0415", 1, "Licensure", "B3B_0277_MA_LICENSURE_APPLICATION_MECHANICS",
      "Exam applicant의 current name이 birth record와 다르면 written name-change notice를 포함한 complete application이 필요하고 incomplete application은 고려되지 않을 수 있다.",
      "Pharmacist licensure applicant", "birth record와 current name 불일치", "MA", "substantive eligibility와 application completeness는 별도이다.",
      "누락된 name-change documentation이 application 처리에 미치는 결과를 판단한다.", ["MA-LICENSURE-APPLICATION-MECHANICS"],
      ["MA-Q-0277"], "기존 문항은 birth proof와 fee refund였고 name-change completeness를 다루지 않았다.",
      ["exception_condition_documentation"], "SBA", 3, False),

    s("MA-Q-0416", 2, "Collaborative practice", "CDTM_REFERRAL_MEANING_BY_SETTING",
      "Community-pharmacy CDTM에는 patient identity/address, authorized diagnoses, allergies, consent statement, specific instructions를 포함한 individual written referral가 필요하다.",
      "CDTM pharmacist", "불완전 community referral 수령", "MA", "hospital consultation referral 개념과 community written-referral contents를 구분한다.",
      "setting을 식별한 뒤 누락된 referral content가 authority를 열어 주는지 판단한다.", ["MA-CDTM-REFERRAL-BY-SETTING"],
      ["MA-Q-0304"], "기존 문항은 setting별 referral form만 물었고 community content completeness를 다루지 않았다.",
      ["collaborative_practice_scope_and_lifecycle"], "SBA", 5, False),
    s("MA-Q-0417", 2, "Patient care", "DUR_RESPONSE_MEASURES_AND_DOCUMENTATION",
      "DUR finding에 대한 clinical response는 pharmacist가 결정해야 하고, 선택한 measure가 prescriber/patient consultation 중 무엇이든 pharmacist는 그 measure를 문서화해야 한다.",
      "Pharmacist and certified technician", "DUR alert가 발생하고 technician이 해결을 제안", "MA", "response measure의 선택은 open-ended이지만 documentation은 mandatory이다.",
      "actor scope를 먼저 판정한 뒤 pharmacist response와 documentation consequence를 적용한다.", ["MA-DUR-RESPONSE-DOCUMENTATION", "MA-CERT-TECH-SCOPE"],
      ["MA-Q-0075"], "기존 bank에는 DUR response-documentation family RELEASED 문항이 없고 technician-role interaction도 미검증이다.",
      ["actor_role_distinctions", "exception_condition_documentation", "natural_multi_rule_scenarios"], "SATA", 5, True),
    s("MA-Q-0418", 2, "Patient care", "COUNSELLING_RECORD_PRESUMPTION",
      "Off-site delivery에는 toll-free pharmacist access와 container-label number가 필요하며, failure-to-accept counseling record가 없으면 counseling 제공의 statutory presumption이 생긴다.",
      "Dispensing pharmacist", "home delivery 후 counseling record 검토", "MA", "remote-access compliance와 evidentiary presumption은 서로 다른 판단이다.",
      "delivery pathway 충족 여부와 absence-of-refusal-record presumption을 차례로 적용한다.", ["MA-COUNSELING-REMOTE-DELIVERY", "MA-COUNSELING-RECORD-PRESUMPTION"],
      ["MA-Q-0213"], "기존 문항은 toll-free number placement만 물었고 counseling-record presumption과 결합하지 않았다.",
      ["prescription_validity_label_delivery", "exception_condition_documentation", "natural_multi_rule_scenarios"], "SBA", 5, True),
    s("MA-Q-0419", 2, "Patient care", "B3B_0285_MA_CONSULTATION_AREA_ACCESS",
      "Patient consultation area는 designated signage와 confidential visual/auditory privacy를 제공해야 한다.",
      "Pharmacist manager", "consultation area 설치 또는 점검", "MA", "physical accessibility와 privacy/signage 조건을 분리한다.",
      "접근 경로가 적법해도 privacy 또는 signage 결함이 남는지 판단한다.", ["MA-COUNSELING-CONSULTATION-AREA"],
      ["MA-Q-0285"], "기존 문항은 dispensing area를 통과하는 접근 경로만 다뤘고 privacy/signage를 다루지 않았다.",
      ["exception_condition_documentation"], "SATA", 4, False),
    s("MA-Q-0420", 2, "Professional conduct", "B3B_0291_MA_INSTITUTIONAL_DISPENSING",
      "Drug Store licence가 없는 hospital/clinic pharmacy는 employee spouse 또는 child에게도 employee와 같은 household에 사는 경우에만 dispense할 수 있다.",
      "Institutional pharmacist", "employee 가족에게 outpatient dispensing", "MA", "가족관계만으로 충분하지 않고 same-household condition이 필요하다.",
      "recipient relationship과 household fact를 함께 적용한다.", ["MA-CONDUCT-INSTITUTIONAL-DISPENSING"],
      ["MA-Q-0291"], "기존 문항은 별거 adult sibling이었고 spouse/child의 household condition을 직접 검증하지 않았다.",
      ["actor_role_distinctions", "precise_qualifier_and_scope_wording"], "SBA", 4, False),
    s("MA-Q-0421", 2, "Confidentiality", "LICENSEE_CONFIDENTIALITY_AFFIRMATIVE_DUTY",
      "Licensee에게는 confidential information을 보호할 의무와 unauthorized disclosure를 하지 않을 병렬 의무가 있다.",
      "Pharmacist licensee", "patient profile 정보를 제3자에게 직접 전달", "MA", "passive protection failure와 affirmative disclosure를 구분한다.",
      "행위가 두 confidentiality limbs 중 어느 의무를 위반하는지 식별한다.", ["MA-LICENSEE-CONFIDENTIALITY"],
      ["MA-Q-0316"], "기존 문항은 disclosure 없이 정보가 노출된 보호 실패만 다뤘다.",
      ["actor_role_distinctions"], "SBA", 4, False),
    s("MA-Q-0422", 2, "Pharmacist administration", "PHARMACIST_INDIVIDUAL_COMPETENCE_SCOPE",
      "개인 pharmacist가 충분히 훈련됐더라도 product 또는 act가 current pharmacist administration scope 밖이면 수행할 수 없다.",
      "Pharmacist", "훈련된 pharmacist가 current eligible list 밖 medication 투여를 요청받음", "MA", "individual competence와 legally recognized/eligible scope는 누적 요건이다.",
      "개인 자격을 확인한 뒤 product-specific legal scope를 별도로 적용한다.", ["MA-PHARMACIST-COMPETENCE-SCOPE", "MA-ADMIN-ELIGIBLE-MEDICATIONS"],
      ["MA-Q-0321"], "기존 문항은 profession-wide 허용 act에 개인 training이 없는 반대 상황이었다.",
      ["actor_role_distinctions", "natural_multi_rule_scenarios"], "SATA", 5, True),
    s("MA-Q-0423", 2, "Pharmacist administration", "ADMINISTRATION_PRESCRIPTION_NOTATION_AND_CONTACT",
      "Current DCP guidance의 post-administration prescriber communication은 strongly encouraged이며 statutory validity condition 또는 SHALL duty로 변환할 수 없다.",
      "Pharmacist", "적법한 administration 후 record 송부 지연", "MA", "best practice/should/encouraged 언어와 mandatory law를 구분한다.",
      "qualifier를 정확히 읽고 administration의 적법성과 권고된 후속 communication을 분리한다.", ["MA-ADMIN-PRESCRIPTION-NOTATION"],
      ["MA-Q-0330"], "기존 문항은 pre-administration notation/contact였고 post-administration communication의 법적 강도를 다루지 않았다.",
      ["precise_qualifier_and_scope_wording"], "SBA", 4, False),
    s("MA-Q-0424", 2, "Prescription validity", "EXP1_0121_OUTSTATE_III_VI",
      "Out-of-state Schedule III-VI prescription은 30 days 내여야 하고 pharmacist는 모두 authentic/valid 판단을 하지만 별도 prescriber verification 문구는 Schedule III-V에 적용되고 VI에는 적용되지 않는다.",
      "Pharmacist", "timely out-of-state Schedule VI prescription 수령", "MA + FEDERAL", "general authenticity judgment와 III-V-only additional verification을 구분한다.",
      "federal/MA schedule을 분류하고 issue-date window와 schedule-specific verification을 적용한다.", ["MA-RX-OUTSTATE-III-VI", "FED-CS-SCHEDULES"],
      ["MA-Q-0027", "MA-Q-0034"], "기존 문항은 verified 또는 late Schedule IV만 다뤘고 Schedule VI distinction을 다루지 않았다.",
      ["federal_state_integrated_application", "prescription_validity_label_delivery", "natural_multi_rule_scenarios"], "SBA", 5, True),
    s("MA-Q-0425", 2, "Medication returns", "MANDATORY_VERSUS_DISCRETIONARY_RETURN_ACCEPTANCE",
      "Pharmacy가 이전에 dispensed한 medication이 suspected defective/contaminated이면 return을 받아야 하고 inventory로 되돌리지 말고 quarantine/dispose해야 한다.",
      "Pharmacist", "환자가 suspected defective product 반환", "MA", "ordinary therapy-change return과 mandatory suspected-defect return을 구분한다.",
      "acceptance duty를 판정한 뒤 accepted product의 quarantine consequence를 적용한다.", ["MA-RETURN-ACCEPTANCE-DUTY", "MA-RETURN-QUARANTINE"],
      ["MA-Q-0317", "MA-Q-0088"], "기존 문항은 dispensing error 또는 정상 반품이었고 suspected-defect acceptance와 quarantine을 함께 다루지 않았다.",
      ["exception_condition_documentation", "natural_multi_rule_scenarios"], "SATA", 4, True),
    s("MA-Q-0426", 2, "Professional conduct", "ANTI_CIRCUMVENTION_STANDARD",
      "허용되지 않는 administration route를 여러 형식적 단계로 나누어 우회하도록 설계한 arrangement는 각 단계가 외형상 허용돼 보여도 금지된다.",
      "Pharmacist licensee", "administration route 제한을 피하기 위한 multi-step arrangement", "MA", "direct/indirect circumvention과 실제 statutory route scope를 함께 본다.",
      "route가 허용되는지 판단하고 arrangement의 목적이 restriction 우회인지 평가한다.", ["MA-CONDUCT-ANTI-CIRCUMVENTION", "MA-ADMINISTER-STATUTORY-ROUTES"],
      ["MA-Q-0295"], "기존 문항은 prescription-transfer sequence였고 administration-route workaround를 다루지 않았다.",
      ["natural_multi_rule_scenarios", "precise_qualifier_and_scope_wording"], "SBA", 5, True),
    s("MA-Q-0427", 2, "Medication returns", "T2_0225_MA_DRUG_RETURN_REUSE_DISTINCT",
      "Prepared but never dispensed medication만 return-to-stock pathway를 사용할 수 있고 original patient container 또는 필수 identifiers/filled expiration을 갖춘 적절한 container와 recall safeguard가 필요하다.",
      "Pharmacist", "pickup되지 않은 prescription을 reusable inventory로 유지", "MA", "previously dispensed return과 never-dispensed return-to-stock을 구분한다.",
      "threshold status를 확인하고 container/record safeguards를 적용한다.", ["MA-RETURN-TO-STOCK"],
      ["MA-Q-0225"], "기존 문항은 manufacturer stock bottle prohibition만 다뤘고 alternative container safeguards를 다루지 않았다.",
      ["exception_condition_documentation"], "SATA", 4, False),

    s("MA-Q-0428", 3, "Prescription transfer", "EXP1_0120_RX_TRANSFER_REQUIREMENTS",
      "Massachusetts Schedule VI prescription은 remaining refills가 있어도 issue 후 1년을 넘으면 transfer할 수 없다.",
      "Receiving pharmacist", "13개월 된 Schedule VI prescription transfer 요청", "MA", "federal controlled schedule intuition과 Massachusetts Schedule VI one-year ceiling을 구분한다.",
      "classification을 확인하고 act-specific transfer consequence를 적용한다.", ["MA-RX-TRANSFER", "MA-SCHEDULE-VI"],
      ["MA-Q-0120", "MA-Q-0397"], "기존 문항은 10-month transfer 또는 fee/agency였고 expired transfer ceiling을 다루지 않았다.",
      ["prescription_validity_label_delivery", "natural_multi_rule_scenarios"], "SATA", 5, True),
    s("MA-Q-0429", 3, "Dispensing requirements", "B3E2_CUSTOMER_IDENTIFIER_HARDSHIP",
      "Customer Identifier duty는 Schedule II-V와 formally designated additional drug dispensing에 적용되며 일반 Schedule VI 전체에 자동 적용되지 않는다.",
      "Dispensing pharmacist", "Schedule VI product에 identifier 요구 여부 판단", "MA", "schedule label과 additional-drug designation을 분리하고 특정 drug name은 사용하지 않는다.",
      "dispensing 대상이 enumerated scope에 들어가는지 판정한다.", ["MA-RX-CUSTOMER-IDENTIFIER"],
      ["MA-Q-0379"], "기존 문항은 hardship cure 절차였고 scope boundary를 다루지 않았다.",
      ["precise_qualifier_and_scope_wording", "controlled_substance_lifecycle_and_actor"], "SATA", 5, False),
    s("MA-Q-0430", 3, "Dispensing requirements", "B3E2_NDC_RECORDING_FALLBACK",
      "Solely-generic-name product에 NDC가 없고 manufacturer도 식별 불가하면 distributor, packer 또는 repacker name으로 ordered fallback한다.",
      "Dispensing pharmacist", "NDC와 manufacturer name이 모두 없는 generic product 기록", "MA", "fallback sequence를 임의로 건너뛸 수 없다.",
      "available identifiers를 순서대로 검사해 기록할 대체 정보를 고른다.", ["MA-RX-NDC-RECORDING"],
      ["MA-Q-0375"], "기존 문항은 manufacturer와 repacker가 모두 있는 경우였고 manufacturer-absent branch를 다루지 않았다.",
      ["prescription_validity_label_delivery", "exception_condition_documentation"], "SBA", 4, False),
    s("MA-Q-0431", 3, "Dispensing requirements", "B3E2_OFFSITE_PROCESSING_VERIFICATION",
      "Offsite processing이 Board-licensed pharmacy에서 수행되면 별도 Massachusetts-pharmacist verification 대신 alternative condition을 충족할 수 있다.",
      "Dispensing pharmacist", "Board-licensed offsite pharmacy가 처리한 medication 수령", "MA", "MA-pharmacist verification과 Board-licensed-site processing은 alternatives이며 사후 inspection과 동일하지 않다.",
      "offsite actor/site status를 확인해 어느 alternative가 충족됐는지 판정한다.", ["MA-RX-OFFSITE-PROCESSING"],
      ["MA-Q-0378"], "기존 문항은 unlicensed out-of-state site와 after-the-fact inspection이었고 licensed-site alternative를 다루지 않았다.",
      ["actor_role_distinctions", "precise_qualifier_and_scope_wording"], "SBA", 5, False),
    s("MA-Q-0432", 3, "Controlled substances", "B3F_PARTIAL_FILL_DEADLINE_PATHWAY",
      "Patient-requested Schedule II partial-fill remainder는 initial partial을 한 same pharmacy에서 issue date 후 30 days 이내에만 dispense할 수 있다.",
      "Dispensing pharmacist", "다른 pharmacy 또는 day 31에 remainder 요청", "MA + FEDERAL", "patient-request pathway를 stock-shortage 72-hour 및 out-of-state 5-day branch와 구분한다.",
      "trigger를 분류하고 federal permission과 Massachusetts same-pharmacy/issue-date conditions를 함께 적용한다.", ["FED-CII-PARTIAL-PATIENT", "MA-CII-PARTIAL-FILL-PATHWAY-LIMITS"],
      ["MA-Q-0401"], "기존 문항은 5-day rule의 in-state applicability를 물었고 same-pharmacy/day-30 combined consequence를 다루지 않았다.",
      ["federal_state_integrated_application", "natural_multi_rule_scenarios"], "SBA", 5, True),
    s("MA-Q-0433", 3, "Dispensing", "B3F_EMERGENCY_SUBSTITUTION_DEVIATION",
      "Medical emergency에서 no-substitution이 없고 less-expensive interchangeable product가 unavailable이면 brand as written을 dispense할 수 있으며 emergency record와 purchaser written acceptance가 필요하다.",
      "Dispensing pharmacist", "generic unavailable medical emergency", "MA", "no-substitution + brand unavailable branch의 반대 방향 deviation이다.",
      "exception direction을 확인하고 record 및 acceptance conditions를 적용한다.", ["MA-INTERCHANGE-MEDICAL-EMERGENCY"],
      ["MA-Q-0391"], "기존 문항은 no-substitution brand unavailable branch였고 reverse branch를 다루지 않았다.",
      ["exception_condition_documentation", "precise_qualifier_and_scope_wording"], "SATA", 4, False),
    s("MA-Q-0434", 3, "Prescription format", "EXP1_0118_RX_REQUIRED_ELEMENTS",
      "Controlled-substance prescription의 practitioner registration number 누락은 Schedule II pharmacist face endorsement로 cure되지 않는다; 두 표시는 서로 다른 actor의 독립 requirements이다.",
      "Dispensing pharmacist", "Schedule II prescription에 prescriber registration number가 없지만 pharmacist endorsement는 있음", "MA", "§22(a) required element와 별도 pharmacist endorsement duty를 혼합하지 않는다.",
      "missing field의 actor와 endorsement actor를 식별해 cure 가능 여부를 판정한다.", ["MA-RX-REQUIRED-ELEMENTS", "MA-CII-PHARMACIST-ENDORSEMENT"],
      ["MA-Q-0118", "MA-Q-0383"], "기존 문항은 patient name/directions 또는 endorsement 자체만 다뤘고 cross-actor non-cure를 다루지 않았다.",
      ["actor_role_distinctions", "prescription_validity_label_delivery", "natural_multi_rule_scenarios"], "SBA", 5, True),

    s("MA-Q-0435", 4, "Compounding", "T2_0218_MA_HAZARDOUS_COMPOUNDING",
      "Hazardous sterile preparation에는 sterile-compounding specialty licensure와 hazardous-drug handling overlay가 모두 적용되며 하나가 다른 하나를 대체하지 않는다.",
      "Pharmacist manager", "ordinary/complex-nonsterile license만 가진 pharmacy가 hazardous sterile preparation 계획", "MA", "patient-specific status나 one license는 다른 framework를 제거하지 않는다.",
      "preparation type과 hazardous status를 분류한 뒤 licensure gate와 operational overlay를 누적 적용한다.", ["MA-STERILE-COMPOUNDING-LICENSE", "MA-HAZARDOUS-COMPOUNDING", "MA-HAZARDOUS-DRUG-HANDLING"],
      ["MA-Q-0216", "MA-Q-0218"], "기존 문항은 nonhazardous sterile licensure 또는 already-licensed hazardous overlay를 각각 분리해 다뤘다.",
      ["compounding_hazardous_personnel_training", "natural_multi_rule_scenarios"], "SATA", 5, True),
    s("MA-Q-0436", 4, "Compounding", "T2_0217_MA_NONSTERILE_COMPOUNDING",
      "Specialized training/environment가 필요한 complex non-sterile activity는 specialty licensure를 요구하고, commercially available product 사용의 patient-specific significant difference는 price alone로 충족되지 않는다.",
      "Pharmacist manager and prescriber", "cost-only rationale로 complex non-sterile preparation 계획", "MA", "activity complexity와 patient-specific significant-difference threshold는 독립 gates이다.",
      "compounding category를 분류하고 commercial-product significant-difference 요건을 별도로 적용한다.", ["MA-COMPLEX-NONSTERILE-LICENSE", "MA-COMPOUNDING-SIGNIFICANT-DIFFERENCE"],
      ["MA-Q-0217", "MA-Q-0219"], "기존 문항은 specialty licence와 cost-only significant difference를 각각 따로 물었고 combined threshold failure를 다루지 않았다.",
      ["compounding_hazardous_personnel_training", "natural_multi_rule_scenarios"], "SBA", 5, True),
    s("MA-Q-0437", 4, "Controlled substance inventory", "EXP1_0127_CS_INVENTORY_COUNTING",
      "Opened Schedule II는 exact count/measure가 필요하고 opened Schedule III-V는 원칙적으로 estimate 가능하지만 1,000 tablets/capsules 초과 container는 exact count가 필요하다.",
      "DEA registrant pharmacist", "mixed-schedule biennial inventory count", "FEDERAL", "schedule과 opened-container size를 함께 적용한다.",
      "각 container의 schedule/status/quantity threshold를 분류해 count method를 선택한다.", ["FED-INVENTORY-COUNT"],
      ["MA-Q-0061"], "기존 문항은 1,200-unit opened Schedule IV만 다뤘고 Schedule II exact rule과 대비하지 않았다.",
      ["controlled_substance_lifecycle_and_actor", "precise_qualifier_and_scope_wording"], "SATA", 5, False),
    s("MA-Q-0438", 4, "Controlled substance procurement", "EXP1_0129_FORM222_RECORDS",
      "Electronic copies of DEA Forms 222는 readily retrievable하면 다른 records와 함께 저장돼도 separately maintained로 간주될 수 있지만 CSOS electronic orders 자체는 별도 retention provision을 따른다.",
      "DEA registrant pharmacist", "Form 222 copy와 CSOS order archive 설계", "FEDERAL", "paper Form 222, electronic Form 222 copy, CSOS electronic order를 같은 객체로 취급하지 않는다.",
      "record object를 먼저 식별하고 해당 maintenance/retention provision을 적용한다.", ["FED-FORM222-RECORDS", "FED-FORM222-ORDER"],
      ["MA-Q-0067", "MA-Q-0128"], "기존 문항은 paper copies 혼합 또는 CSOS ordering validity만 다뤘고 electronic-copy/order distinction을 다루지 않았다.",
      ["exception_condition_documentation", "natural_multi_rule_scenarios"], "SATA", 5, True),
    s("MA-Q-0439", 4, "Controlled substance inventory", "EXP1_0125_INITIAL_CS_INVENTORY",
      "Registrant가 controlled-substance activity를 시작할 때 on-hand stock이 없어도 zero-stock fact를 initial inventory로 기록해야 한다.",
      "New DEA registrant", "controlled-substance activity 개시 시 stock 없음", "FEDERAL", "physical count가 zero라는 사실과 inventory record가 불필요하다는 결론을 구분한다.",
      "inventory trigger가 stock receipt가 아니라 registrant activity start인지 판단한다.", ["FED-INVENTORY-INITIAL"],
      ["MA-Q-0059"], "기존 문항은 first stock activity 시점을 물었고 zero-stock record requirement를 다루지 않았다.",
      ["controlled_substance_lifecycle_and_actor"], "SBA", 3, False),
]


def main() -> int:
    rules = {record["rule_id"]: record for _, record in load_records(DATA / "rules")}
    families = {item["family_id"]: item for item in load_json(DATA / "exam_style" / "question_family_matrix.json")["families"]}
    headroom = {item["family_id"]: item for item in load_json(ROOT / "audits" / "coverage" / "2026-09-01" / "BATCH4-FAMILY-HEADROOM.json")["all_families"]}
    for slot in SLOTS:
        slot["official_authority"] = [
            {
                "rule_id": rule_id,
                "content_version": rules[rule_id]["content_version"],
                "content_hash": rules[rule_id]["content_hash"],
                "last_verified": rules[rule_id]["last_verified"],
                "authorities": rules[rule_id]["authority"],
            }
            for rule_id in slot["rule_ids"]
        ]
        slot["family_headroom_at_review"] = headroom[slot["family_id"]]["released_headroom"]
        slot["family_max_questions"] = families[slot["family_id"]]["max_questions_in_final_bank"]

    write_json(
        OUTPUT,
        {
            "report_type": "B4_A_PROPOSITION_MAP_FINAL",
            "status": "FINAL_REVIEWED_FOR_AUTHORING",
            "recorded_on": "2026-09-01",
            "controller_issue": 121,
            "source_live_main_sha": SOURCE_MAIN_SHA,
            "question_range": {"first": "MA-Q-0407", "last": "MA-Q-0439", "count": 33},
            "area_allocation": {"1": 9, "2": 12, "3": 7, "4": 5},
            "planned_item_types": {
                "SBA": sum(slot["planned_question_type"] == "SBA" for slot in SLOTS),
                "SATA": sum(slot["planned_question_type"] == "SATA" for slot in SLOTS),
            },
            "multi_rule_count": sum(slot["multi_rule"] for slot in SLOTS),
            "inputs": {
                "proposition_census": "audits/coverage/2026-09-01/BATCH4-PROPOSITION-CENSUS.json",
                "family_headroom": "audits/coverage/2026-09-01/BATCH4-FAMILY-HEADROOM.json",
                "real_exam_signals": "audits/coverage/2026-09-01/BATCH4-REAL-EXAM-SIGNAL-REPORT.json",
                "released_bank_count": 366,
            },
            "authority_review": {
                "reviewed_slots": 33,
                "initial_pass": 30,
                "initial_revise": 3,
                "initial_reject": 0,
                "resolved_revisions": {
                    "MA-Q-0434": "§22(a)의 practitioner registration number 하나로 고정하고 pharmacist endorsement와 분리했다.",
                    "MA-Q-0438": "electronic Form 222 copy와 CSOS electronic order를 명시적으로 분리했다.",
                    "MA-Q-0439": "과도한 general-inventory 명제를 제거하고 zero-stock initial inventory proposition으로 교체했다.",
                },
                "final_unresolved_authority_risks": 0,
            },
            "controls": {
                "forbidden_rule_ids": ["MA-MH-SUD-ADMIN"],
                "forbidden_rule_ids_used": [],
                "hold_questions_preserved": ["MA-Q-0172"],
                "recalled_actual_question_content_retained": 0,
                "candidate_reports_used_only_as_abstract_signals": True,
                "cdtm_slot_count": 1,
                "area4_compounding_slot_count": 2,
                "multi_rule_target": "10-14 when natural",
                "novelty_rule": "actor, trigger, exception, jurisdiction, timing, documentation consequence, setting, or legal interaction must materially differ; drug-name substitution alone is insufficient",
            },
            "slots": SLOTS,
        },
    )
    print(f"wrote {OUTPUT.relative_to(ROOT)} with {len(SLOTS)} slots")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
